### PR TITLE
Test ECC Root CA

### PR DESCRIPTION
**Pull request by tpicloud**

### CODE REVIEW

**Comment by tpicloud** [comment]
Hello, may I know when the Dodo script will run?

**Comment by tpicloud** [comment]
Thank you! We see that certificate has been added to Dodo.
However, when we tried to submit the root certificate to Dodo for testing, we got following error:
`unable to submit certificate to log, HTTP error 400 Bad Request: { "error_message": "untrusted self-signed certificate", "success": false }`

Any idea?

**Comment by robstradling** [comment]
@tpicloud Your certificate has been added to this GitHub repository, but the Sectigo ops team has not yet deployed the update.  This may take a few days.

**Comment by robstradling** [comment]
@tpicloud The update has now been deployed to Dodo.

**Comment by tpicloud** [comment]
@robstradling Great! It is working now! Thank you!
Have a nice day :)

**Pull request merged**
