### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by connellyt**
Request inclusion of Test US Federal TLS Root CA.

### CODE REVIEW

**Comment by ryancdickson** [comment]
@robstradling - Hi Rob, any idea when the Dodo update script will run next?

**Comment by robstradling** [comment]
@ryancdickson @connellyt Sorry for the delay.  We'll aim to get this root added to Dodo this week.

**Comment by ryancdickson** [comment]
Thanks, @robstradling! We appreciate it.

**Comment by robstradling** [comment]
@ryancdickson @connellyt This root has now been added to Dodo.  I've add-chain'd the root certificate itself to confirm it's working: see https://crt.sh/?id=1305347383

**Comment by robstradling** [comment]
@ryancdickson @connellyt This root is being removed from Dodo in order to avoid it from [being spammed into uselessness](https://datatracker.ietf.org/doc/html/rfc6962#:~:text=being%20spammed%20into%20uselessness).  It has come to our attention that (other than the root certificate itself) the only certificate submitted to Dodo that chains to this root is a Subordinate CA certificate whose corresponding private key is publicly known.

**Comment by connellyt** [comment]
@robstradling Thanks for the information. We've already destroyed that CA and corresponding private keys.

**Pull request merged**
